- hosts: kodi
  vars_files:
    - secrets.yml
  become: True
  pre_tasks:
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
  roles:
     - kodi
