# Add specified repository into sources list.
- name: Add Apt signing key for rapsbian buster custom build of lastest kodi
  apt_key:
    url: http://pipplware.pplware.pt/pipplware/key.asc
    state: present
- name:  Add repo for raspbian buster custom build of lastest kodi
  apt_repository:
    repo: deb http://pipplware.pplware.pt/pipplware/dists/buster/main/binary /
    state: present
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
- name: Update all packages to the latest version
  apt:
    upgrade: dist
- name: Install kodi and all dependencies
  apt:
    name: kodi
- name: copy systemd kodi standalone service script
  copy:
    src: "{{role_path}}/files/kodi.service"
    dest: /lib/systemd/system/kodi.service
    owner: root
    group: root
    mode: '0644'
- name: force reload of systemd and enable/start kodi
  systemd:
    name: kodi
    enabled: yes
    daemon_reload: yes
  become: yes
# https://kwartix.wordpress.com/2019/05/13/netflix-raspberry-et-kodi/ 
- name: Download additional plugins to /home/pi/
  get_url:
    url: "{{item}}"
    dest: /home/pi/
  with_items:
    - "https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.0.zip"
    - "http://dev.grantgarrison.com/projects/script.parsec.zip"
    - "https://github.com/wackerl91/luna/releases/download/v0.7.0-rc7/script.luna-0.7.0-rc7.zip"
- name: reboot raspberri pi
  shell: sleep 5s && sudo /sbin/shutdown -r now
  async: 1
  poll: 0
