# Add specified repository into sources list.
- name: Add Apt signing key for rapsbian buster custom build of lastest kodi
  apt_key:
    url: http://pipplware.pplware.pt/pipplware/key.asc
    state: present
- name:  Add repo for raspbian buster custom build of lastest kodi
  apt_repository:
    repo: deb http://pipplware.pplware.pt/pipplware/dists/buster/main/binary /
    state: present
- name: Install kodi and my choosen dependencies (i have no need for pvr but there are available on the repositories)
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - kodi
      - kodi-audiodecoder-*
      - kodi-inputstream-adaptive
      - kodi-peripheral-joystick
- name: copy systemd kodi standalone service script
  copy:
    src: "{{role_path}}/files/kodi.service"
    dest: /lib/systemd/system/kodi.service
    owner: root
    group: root
    mode: '0644'
- name: force reload of systemd and enable/start kodi
  systemd:
    name: kodi
    enabled: yes
    daemon_reload: yes
  become: yes
- name: Download additional plugins to /home/pi/
  get_url:
    url: "{{item}}"
    dest: /home/pi/
  with_items:
    - "https://github.com/castagnait/repository.castagnait/raw/master/repository.castagnait-1.0.0.zip"
    - "http://dev.grantgarrison.com/projects/script.parsec.zip"
    - "https://github.com/wackerl91/luna/releases/download/v0.7.0-rc7/script.luna-0.7.0-rc7.zip"
- name: reboot raspberri pi
  shell: sleep 5s && /sbin/shutdown -r now
  async: 1
  poll: 0
  become: true
